apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jumpstarter-secrets-access-role
  namespace: auto-jumpstarter
rules:
  - apiGroups: [""]
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jumpstarter-secrets-access-jumpstarter-users
  namespace: auto-jumpstarter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jumpstarter-secrets-access-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: jumpstarter-users
