apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jumpstarter-gitops-cluster-role
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jumpstarter-gitops-cluster-role-binding
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jumpstarter-gitops-cluster-role
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auto-exporters-gitops-cluster-admin
  namespace: auto-exporters
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops