apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jumpstarter-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: jumpstarter-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: jumpstarter-operator.v0.9.0
