apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: "auto-devspaces"
  namespace: "auto-devspaces"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
      #clusterRoles:
      #  - platform-admin-access-role
      #  - pipelines-admin-access-role

    dashboard:
      logLevel: ERROR

    metrics:
      enable: true

  containerRegistry: {}

  devEnvironments:
    startTimeoutSeconds: 300

    secondsOfRunBeforeIdling: -1
    secondsOfInactivityBeforeIdling: 1800

    maxNumberOfWorkspacesPerUser: -1
    maxNumberOfRunningWorkspacesPerUser: 1
    maxNumberOfRunningWorkspacesPerCluster: -1

    disableContainerRunCapabilities: false #true
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: container-build

    # make sure the devspaces instance is scheduled on one of the builder nodes
    nodeSelector:
      auto.node-role/builder: "true"
    
    #tolerations:
    #  - key: "architecture" # TODO the correct key ?
    #    operator: "Equal"
    #    value: "arm" # TODO the correct value, arm64 ?
    #    effect: "NoSchedule"

    containerRunConfiguration:
      containerSecurityContext:
        procMount: Unmasked
        capabilities:
          add:
            - SETGID
            - SETUID
        allowPrivilegeEscalation: true
      openShiftSecurityContextConstraint: container-run

    defaultContainerResources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "500m"
        memory: 1Gi

    ignoredUnrecoverableEvents:
      - FailedScheduling

    defaultNamespace:
      autoProvision: false
    #  template: devspaces-<username>

    user:
      #clusterRoles:
      #  - platform-access-role
      #  - pipelines-access-role

    imagePullPolicy: Always # IfNotPresent
    deploymentStrategy: Recreate

    persistUserHome:
      enabled: true
      
    storage:
      pvcStrategy: per-user
      perUserStrategyPvcConfig:
        claimSize: 10Gi
        # storageClass: "your-storage-class"  # Uncomment and set to your preferred storage class

  gitServices: {}

  networking:
    auth:
      advancedAuthorization:
        allowGroups:
          - "platform-admins"
          - "platform-users"
      gateway:
        kubeRbacProxy:
          logLevel: 0
        oAuthProxy:
          cookieExpireSeconds: 86400
        traefik:
          logLevel: INFO
