kind: Namespace
apiVersion: v1
metadata:
  name: admin-devspaces   
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    che.eclipse.org/username: admin