apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pr-pac-role
  labels:
    app.kubernetes.io/part-of: rhas-platform
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
  - apiGroups: [""]
    resources:
      - services
    verbs:
      - get
      - list
      - watch