apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-access-role
  labels:
    app.kubernetes.io/part-of: rhas-platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: [""]
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipelines-access-role
  labels:
    app.kubernetes.io/part-of: rhas-platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: ["tekton.dev"]
    resources:
      - pipelines
      - pipelineruns
      - taskruns
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["pipelinesascode.tekton.dev"]
    resources:
      - repositories
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - services
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
